python-six is required in the build process
the build error log is:

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "./ovsdb/ovsdb-idlc.in", line 8, in <module>
    import ovs.json
  File "/root/rpmbuild/BUILD/openvswitch-2.6.1/python/ovs/json.py", line 21, in <module>
    import six
ImportError: No module named six
```