datapath/linux: add KCFLAGS var to modules Makefile.main.in
This is mostly required because of GCC 4.9 which seems
to error out with:
  openvswitch/datapath/linux/datapath.c:2108:10:
       error: macro "DATE" might prevent reproducible builds

We would have wanted to add '-Wno-error=date-time' directly
but that would be too specific, so we decided to add
a generic make flag and configure it with what we need.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>