Windows: Fix broken build caused by a bad file extension
The compiler (cl) complains:
`ovsdb/ovsdb-server.c(689) : fatal error C1083:
    Cannot open include file: 'ovsdb/_server.ovsschema.inc':
       No such file or directory`
(https://ci.appveyor.com/project/blp/ovs/build/1.0.4079#L2586)

Generated compiler objects have the extension `.obj` on Windows.

This patch switches to `$(OBJEXT)` instead, so the schema will be generated.

Signed-off-by: Alin Gabriel Serdean aserdean@ovn.org
Acked-by: Ben Pfaff <blp@ovn.org>