tests/oss-fuzz: Fix the arguments of parse_tcp_flags.
tests/oss-fuzz/flow_extract_target.c:59:53:
     error: too few arguments to function call, expected 4, have 1
         uint16_t tcp_flags = parse_tcp_flags(&packet);
                              ~~~~~~~~~~~~~~~        ^

Fixes: e7e9973b80d3 ("dpif-netdev: Forwarding optimization for flows with a simple match.")
Reported-at: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43498
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
Acked-by: Aaron Conole <aconole@redhat.com>