Revert "Work around Python/C JSON unicode differences"
This reverts commit fdf76010bf1b3c95bafd1cb02c7b06b231bfad70.
The commit caused large numbers of test failures like the following:

../../tests/unixctl-py.at:19: $PYTHON2 $srcdir/appctl.py --timeout 20 -t ovs-vswitchd exit
--- /dev/null	2018-10-15 18:36:00.316000000 +0000
+++ /home/travis/build/openvswitch/ovs/openvswitch-2.10.1/_build/tests/testsuite.dir/at-groups/554/stderr	2018-10-15 20:58:09.726902864 +0000
@@ -0,0 +1,14 @@
+Traceback (most recent call last):
+  File "../../../../tests/appctl.py", line 75, in <module>
+    main()
+  File "../../../../tests/appctl.py", line 60, in main
+    err_no, error, result = client.transact(args.command, args.argv)
+  File "/home/travis/build/openvswitch/ovs/openvswitch-2.10.1/python/ovs/unixctl/client.py", line 39, in transact
+    error, reply = self._conn.transact_block(request)
+  File "/home/travis/build/openvswitch/ovs/openvswitch-2.10.1/python/ovs/jsonrpc.py", line 333, in transact_block
+    error, reply = self.recv_block()
+  File "/home/travis/build/openvswitch/ovs/openvswitch-2.10.1/python/ovs/jsonrpc.py", line 316, in recv_block
+    error, msg = self.recv()
+  File "/home/travis/build/openvswitch/ovs/openvswitch-2.10.1/python/ovs/jsonrpc.py", line 275, in recv
+    if six.PY3 or ovs.json.PARSER == ovs.json.PARSER_PY:
+AttributeError: 'module' object has no attribute 'PARSER'
../../tests/unixctl-py.at:19: exit code was 1, expected 0

See, e.g. https://api.travis-ci.org/v3/job/441866429/log.txt

Signed-off-by: Ben Pfaff <blp@ovn.org>