sflow: Always enable _BSD_SOURCE.
sFlow library is using BSD-style types like u_char that require
_BSD_SOURCE to be defined.

Also adding _DEFAULT_SOURCE, because _BSD_SOURCE cannot be used
without it with glibc > 2.19:

  error: "_BSD_SOURCE and _SVID_SOURCE are deprecated,
          use _DEFAULT_SOURCE"

Acked-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>