ovsdb-doc: Add build dependency on dirs.py.
ovsdb-doc includes python code that requires dirs.py to exist.
This change fixes broken 'make manpage-check' target:

  # make manpage-check
  Traceback (most recent call last):
  File "./ovsdb/ovsdb-doc", line 25, in <module>
    import ovs.db.schema
  File "/root/ovs/python/ovs/db/schema.py", line 19, in <module>
    import ovs.db.types
  File "/root/ovs/python/ovs/db/types.py", line 18, in <module>
    import ovs.db.data
  File "/root/ovs/python/ovs/db/data.py", line 22, in <module>
    import ovs.jsonrpc
  File "/root/ovs/python/ovs/jsonrpc.py", line 21, in <module>
    import ovs.poller
  File "/root/ovs/python/ovs/poller.py", line 23, in <module>
    import ovs.vlog
  File "/root/ovs/python/ovs/vlog.py", line 25, in <module>
    import ovs.dirs
  ModuleNotFoundError: No module named 'ovs.dirs'

Fixes: 943c4a325045 ("python: set ovs.dirs variables with build system values")
Acked-by: Mark Gray <mark.d.gray@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>