route-table-bsd: Remove unused vlog definition
Complained by clang 3.4.

lib/route-table-bsd.c:35:1: error: unused variable 'THIS_MODULE'
      [-Werror,-Wunused-const-variable]
VLOG_DEFINE_THIS_MODULE(route_table);
^
./lib/vlog.h:176:42: note: expanded from macro 'VLOG_DEFINE_THIS_MODULE'
        static struct vlog_module *const THIS_MODULE = &VLM_##MODULE

Acked-by: Ben Pfaff <blp@nicira.com>
Signed-off-by: YAMAMOTO Takashi <yamamoto@valinux.co.jp>