util: Add non-NULL format assertion to xvasprintf.
For some reason GCC 14.1.1 on Fedora 41 assumes that format can
be NULL and emits a warning:

 lib/util.c: In function 'xvasprintf':
 lib/util.c:229:14: error: null format string
   229 |     needed = vsnprintf(NULL, 0, format, args);
       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I didn't find any users where this can be true.  Adding an
assertion to silence the warning.  In the worst case we'll
find out where it is being called incorrectly.

Acked-by: Mike Pattrick <mkp@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>