compiler.h: Don't use asm and typeof with non-GNU compilers.
'asm' is a GNU extension.  Compilers without GNU extensions do not
understand it:

  dpif-netdev-perf.h:225:5: error: use of undeclared identifier 'asm'
      asm volatile("rdtsc" : "=a" (l), "=d" (h));

Redefining asm as __asm__ for non-C++ compilers that do not have it
defined.  While at it, also add typeof definition.  It doesn't need
a check for C++, because it's not a keyword in C++.

Acked-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>