travis: Install libnuma dependency for DPDK.
libnuma is a default dependency for DPDK 17.11 because
CONFIG_RTE_EAL_NUMA_AWARE_HUGEPAGES and CONFIG_RTE_LIBRTE_VHOST_NUMA
are enabled by default for most architectures.
libnuma-dev package installation fixes the DPDK build:

	eal_memory.c:56:18: fatal error:
		numa.h: No such file or directory

CC: Mark Kavanagh <mark.b.kavanagh@intel.com>
Fixes: 5e925ccc2a6f ("netdev-dpdk: DPDK v17.11 upgrade")
Signed-off-by: Ilya Maximets <i.maximets@samsung.com>
Signed-off-by: Ben Pfaff <blp@ovn.org>
Acked-by: Ian Stokes <ian.stokes@intel.com>
Tested-by: Ian Stokes <ian.stokes@intel.com>