ovn: fix build on FreeBSD
The missing include was needed for struct in6_addr.

Otherwise, this build failure would occur.

In file included from ovn/lib/actions.c:23:
ovn/lib/ovn-dhcp.h:163:21: error: field has incomplete type 'struct in6_addr'

Signed-off-by: Thadeu Lima de Souza Cascardo <cascardo@redhat.com>
Signed-off-by: Ben Pfaff <blp@ovn.org>