sparse: Include stddef.h to ensure NULL is defined.
Include stddef.h in include/sparse/sys/socket.h to ensure
that NULL is defined and thus avoid the following sparse warning.

./include/sparse/sys/socket.h:74:15: error: undefined identifier 'NULL'

Signed-off-by: Simon Horman <horms@verge.net.au>
Signed-off-by: Ben Pfaff <blp@nicira.com>