uuid: Fix a warning about zero byte truncation in the template.
Some newer versions of GCC 15 complain:

 lib/uuid.c:308:40: error:
   initializer-string for array of 'char' truncates NUL terminator but
   destination lacks 'nonstring' attribute (37 chars into 36 available)
   [-Werror=unterminated-string-initialization]

 static const char tmpl[UUID_LEN] = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

We could add 1 to the size or use the attribute, but it seems simpler
to just convert the template into a const string pointer.  There
shouldn't be any practical difference as the string will be static
either way.

It's not really a bug, the code is fine as it is, but adding a 'Fixes'
tag just as a reference for backports.

Fixes: c80eac1f85df ("ovn-controller: Tie OpenFlow and logical flows using OpenFlow cookie.")
Acked-by: Eelco Chaudron <echaudro@redhat.com>
Acked-by: Kevin Traynor <ktraynor@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>