datapath: Fix datapath build on Centos 6.5 (2.6.31-431) kernels
The following error is caused by the undefined dev_get_stats64() of kernel
v2.6.32-431. The HAVE_RTNL_LINK_STATS64 does not work because this series
kernel have the "struct rtnl_link_stats64" but neither have 64bit
dev_get_stats() nor dev_get_stats64(), so we should use the compat defined
rpl_dev_get_stats() here.

I just made this patch against branch-2.5 because the master branch are
dropping the support of kernel less than v3.10 now.
----
/root/rpmbuild/BUILD/openvswitch-2.5.1/_default/datapath/linux/vport.c: In function 'ovs_vport_get_stats':
/root/rpmbuild/BUILD/openvswitch-2.5.1/_default/datapath/linux/vport.c:328: error: implicit declaration of function 'dev_get_stats64'
/root/rpmbuild/BUILD/openvswitch-2.5.1/_default/datapath/linux/vport.c:328: warning: assignment makes pointer from integer without a cast
----

Signed-off-by: Wanlong Gao <wanlong.gao@easystack.cn>
Signed-off-by: Jesse Gross <jesse@kernel.org>