perf-counter: Fix 32-bit build break due to incorrect printf specifiers.
Fixes the following warnings from GCC on 32-bit architectures:

    ../lib/perf-counter.c: In function 'perf_counter_to_ds':
    ../lib/perf-counter.c:119:19: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' [-Werror=format]
    ../lib/perf-counter.c:119:19: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'uint64_t' [-Werror=format]

Signed-off-by: Ben Pfaff <blp@nicira.com>
Acked-by: Andy Zhou <azhou@nicira.com>