datapath: Fix datapath compilation error.
  CC [M]  /home/pravin/ovs/cln/datapath/linux/flow_table.o
datapath/linux/flow_table.c: In function ‘masked_flow_lookup’:
datapath/linux/flow_table.c:508:2: warning: passing argument 2 of ‘flow_hash’ makes integer from pointer without a cast
[enabled by default]
  hash = flow_hash(&masked_key, &mask->range);
  ^
datapath/linux/flow_table.c:442:12: note: expected ‘int’ but argument is of type ‘struct sw_flow_key_range *’
 static u32 flow_hash(const struct sw_flow_key *key, int key_start,
            ^
datapath/linux/flow_table.c:508:2: error: too few arguments to function ‘flow_hash’
  hash = flow_hash(&masked_key, &mask->range);
  ^
datapath/linux/flow_table.c:442:12: note: declared here
 static u32 flow_hash(const struct sw_flow_key *key, int key_start,
            ^
make[5]: *** [/home/pravin/ovs/cln/datapath/linux/flow_table.o] Error 1
---8<---

Fixes: bd42c105e71 ("datapath: Backport "openvswitch: Zero flows on
allocation."")

Signed-off-by: Pravin B Shelar <pshelar@nicira.com>